name: ruyi mirror checker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Clone packages-index repository
        run: |
          git clone --depth=1 https://github.com/ruyisdk/packages-index.git packages-index

      - name: Generate mirror check results
        run: |
          uv sync
          uv run python -m checker.generate

      - name: Move generated files to publish directory
        run: |
          mkdir -p /tmp/publish/
          mv ./*.json /tmp/publish/ 2>/dev/null || true

      - name: Git push assets to "hidden" branch
        run: |
          git checkout --orphan hidden
          git rm -rf . 2>/dev/null || true
          git clean -fdx
          cp -r /tmp/publish/* .
          rm -rf /tmp/publish
          rm -rf packages-index
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add status.json
          git commit -m "update mirror check results ($(date -u +"%Y-%m-%d %H:%M %Z"))" || echo "no changes"
          git push origin hidden -f
